### ISSUE TITLE
As a Founder, I want a menu option on the left side bar to view Connections in organized lists by Type (Mentor, Investor, Founder, etc)

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#12]
The founder should be able to click the Connections Link on the side bar and have them organized by the Type of Connection. Here's a visual of the connections screen: 
![image](https://cloud.githubusercontent.com/assets/12280257/7736330/e14dd870-fef7-11e4-9632-a02b8e1be27c.png)

The order of the Connection Lists from left to right will be based on the Founder's Weekly Focus on the Top Bar. Please set the Default (no focus selected) from left to right as:
Mentor
Customer
Founder
Investor

I will provide more detail for the order based on Weekly Focus when we start layering in the Recommendation Logic. Thanks!

**Comment by schrizsz** [comment]
depends #13 #14 #15 #16

**Comment by schrizsz** [comment]
Menu is acting really weird: 
![image](https://cloud.githubusercontent.com/assets/9349216/8149890/ace1d646-12dd-11e5-9beb-2e0c9a158e80.png)
http://recordit.co/p3g6SGHTRJ

**Comment by zachpritchard** [comment]
@VeikoSoomets Minor changes to close out this issue. 
1. When on the connections page, highlight the "Connections" option.
2. When on connections page, the sub-menu (Founders, Mentors, Customers, etc) should remain open.
3. When on any other page, keep it the same. Only show the sub-menu when hovering.

**Comment by schrizsz** [comment]
@VeikoSoomets The menu still does not work properly
From previous comments
@VeikoSoomets Minor changes to close out this issue. 
1. When on the connections page, highlight the "Connections" option.
It is highlighted at first but when I move over the other menus the highlight goes away
2. When on connections page, the sub-menu (Founders, Mentors, Customers, etc) should remain open.
It does not stay open after I go over it with my mouse. As we currently have only 1 expanding submenu I think It is ok if it never closes when I am on one of it's sub pages ( Founders ) or on the main item ( Connections) @zachpritchard do you agree with this?

**Comment by zachpritchard** [comment]
@schrizsz: yes, I agree. Thanks!

**Comment by zachpritchard** [comment]
@schrizsz @VeikoSoomets 

Did you make change to fix this? I'm trying to test it, but the page is loading really slow because of the new data. 

If nothing's changed, please let me know when changes are made. Once done, remove the current "fixing" tag and add "testing" then assign to me. Thanks!

**Comment by zachpritchard** [comment]
From sprint planning 7/8:
- Primary tag only for recommendations & view on profile
- Title, Company on 1 line in the card
     - Truncate title and show when hover
     - Show the entire company
- Areas of Expertise on 3 lines
     - 1 line for title
     - 2 lines for tags
     - hover to see all tags
