### ISSUE TITLE
As a Founder, I want to access the Connectory from the Portal or directly on all browsers so that I can use any browser other than Chrome to access the Connectory

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#17]
We received an email from Mo, a founder, that he was having issues accessing the Connectory. I looked into the issue, and it turns out that the Connectory doesn't work on any browsers besides Chrome. Here's a screenshot from Safari:
![screen shot 2015-05-22 at 7 14 13 pm](https://cloud.githubusercontent.com/assets/12280257/7782066/88d51164-00b8-11e5-8b93-8f9f4d6cecb6.png)
Url: https://portal.alchemistaccelerator.com/ext/connectory_url

This is a core feature on the current portal so please prioritize this bug. Thanks!

**Comment by schrizsz** [comment]
So basically we still have an issue with Safari on some macs?
For me it works fine
![screen shot 2015-05-25 at 19 22 06](https://cloud.githubusercontent.com/assets/9349216/7799786/5e72c7e2-0313-11e5-9e38-76348fca828e.png)

**Comment by zachpritchard** [comment]
@schrizsz I just did another test of all the browsers and it now works on Safari for me. I appreciate the quick response and great job!
