### ISSUE TITLE
Change the link in the side bar for "Connections" to open within the Portal

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#2]
The link is highlighted in the screenshot below:
![screen shot 2015-05-13 at 9 22 31 am](https://cloud.githubusercontent.com/assets/12280257/7615317/cba258f8-f951-11e4-8724-e4d123c5972c.png)

The link should open like current dashboard link in the screenshot shown below:
![screen shot 2015-05-13 at 9 21 45 am](https://cloud.githubusercontent.com/assets/12280257/7615284/835f4b6e-f951-11e4-882e-f921f2d379ad.png)

**Comment by schrizsz** [comment]
accidentially closed with commit message, we should not use this.

**Comment by zachpritchard** [comment]
@schrizsz I'm going to close this issue, but please make the same change on staging. Thanks!
