### ISSUE TITLE
As a Founder, I want to see all the areas of expertise that exist so I can search and choose multiple areas of expertise at once

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#21]
The founder should be able to click a link in the drop, and go to a modal that provides all the options to scroll through. They should also be able to search and select them. After selecting multiple options, they should be able to add them all to their profile at once. 

Here's an image with the link to open the modal with the added link text as red:
![areas_of_expertise-choose_from_all_options_added](https://cloud.githubusercontent.com/assets/12280257/7849325/106d4dde-0489-11e5-9831-b35dbef50171.png)

Here's an image with the actual modal open showing the search bar, scroll bar on the side, and button to add all of the selected options to their profile:
![areas_of_expertise-choose_from_all_options_modal](https://cloud.githubusercontent.com/assets/12280257/7849338/2d52b614-0489-11e5-8887-5cda137f5c65.png)

Please let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard  check on staging-portal, I added the possibility to scroll thru all the tags and select any conveniently on the current dropdown. If this approach is not OK tell me.

**Comment by schrizsz** [comment]
- alphabetical if not searching
- @zachpritchard  will provide help text

**Comment by zachpritchard** [comment]
@schrizsz Help text below:
Please select all the Areas of Expertise that apply to you. You can search for specific Areas in the box or scroll down within the dropdown and click Areas to add them. When you're finished, click the "check" on the right to save them.

**Comment by schrizsz** [comment]
in stage

**Comment by zachpritchard** [comment]
Looks good! Push live whenever you're ready. Let me know when it goes live so I can do one last QA before I close the issue. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard i've put these to live properly (found one detached, local only, branch), please check and close
