### ISSUE TITLE
As a Founder, I want to save fields in my profile and see them reflected immediately so I know the information is being saved

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#23]
The fields for companies and individuals are not being saved immediately when entered. A founder believes it applies to the multi-selection fields. 

Here's the email exchange:

Zach & Kristian,

Just a heads-up, I think the problem is with multi-select fields. I found the values do get saved but is reflected on the profile only after 15 minutes or so. 

Regards
ᐧ

Best Regards,
Ashutosh Pandey
Sales Head, Moxiter
+91-9538847407
+91-80-40921645
Skype : ashutosh142 

This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Moxiter. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.

On Thu, May 28, 2015 at 8:04 AM, Danielle D'Agostaro <danielle@alchemistaccelerator.com> wrote:
Adding our dev team to investigate this issue

Danielle D'Agostaro
Partner & VP, Operations
Alchemist Accelerator
415-527-0158
www.alchemistaccelerator.com

On May 27, 2015, at 7:03 PM, Ashutosh Pandey <ashutosh@moxiter.com> wrote:

Mia,

Tried filling out the details. Some fields are unresponsive / buggy and won't save the values entered.  Will try it again in 30 minutes

Regards

On 28 May 2015 06:56, "Mia Scott" <mia@alchemistaccelerator.com> wrote:
Ashutosh -

We were reviewing the Alchemist Founders Directory and noticed we were missing some information. Would you mind going back to the Founders Directory and filling in the missing fields? We will use this in our communications about you to mentors, customers, and others.

With thanks,

Mia Scott
Alchemist Accelerator
mia@alchemistaccelerator.com

We're about to onboard a bunch of new founders and companies so we need to prioritize new company field functionality. Thanks!

**Comment by schrizsz** [comment]
fixed in live, if I understood the problem correctyl

**Comment by zachpritchard** [comment]
I believe you've corrected it for the most part. I found some other minor issues that I'd like to get fix that go along with fields. When I enter in a new Area of Expertise tag and accept the changes by click the check in the right corner, the selection drop down is still there at times. 

Here's a screenshot of this suspended drop down:
![screen shot 2015-05-28 at 3 44 19 pm](https://cloud.githubusercontent.com/assets/12280257/7873021/2e5110b4-0552-11e5-8768-cac2a8554f68.png)

1. Let's make sure the drop down closes when they save the field

Thanks!

**Comment by schrizsz** [comment]
fixed in live

**Comment by zachpritchard** [comment]
I just checked it out on multiple browsers and looks good. Thanks!
