### ISSUE TITLE
As a PM, I want the sign up process within the portal so that it is simpler for founder and more streamlined for Alchemist

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#25]
When Alchemist accepts a Founder into the Alchemist program, an Alchemist team member will be able to invite this Founder by email to sign up for the Portal. The Founder will click on the link in the invitation email and land on the Welcome Page then continue through entire process shown in the following wireframes.

Welcome Landing Page
![image](https://cloud.githubusercontent.com/assets/12280257/7950074/ad0693f6-094a-11e5-8716-d74669bed5b3.png)

Personal Information
![image](https://cloud.githubusercontent.com/assets/12280257/7950085/bddcd2ee-094a-11e5-88a0-156cd2f0039c.png)
Note: The Areas of Expertise will come from our tags all ready in the system and have the same search options.
All fields will be required on this page.

Company Information
![image](https://cloud.githubusercontent.com/assets/12280257/7950444/9308e620-094f-11e5-9536-51cba121e7db.png)
Notes: The Industry Keywords will come from our tags all ready in the system and have the same search options.
All fields will be required besides Company Logo, Executives Summary Website, LinkedIn Profile, and Twitter.

Team Information
![image](https://cloud.githubusercontent.com/assets/12280257/8412350/2c079a30-1e3e-11e5-9364-acba457aa1dc.png)
Note: The founder should be able to invite their team members at this stage, and send a similar link to their sign up. The invited members will only have to fill out the personal information.
All fields will be required except team member, but they will invite their emails to join.

Additional Information
![image](https://cloud.githubusercontent.com/assets/12280257/7950219/6e67c60e-094c-11e5-8dce-1479d7c4b185.png)
Notes: These fields all exist today. Eventually, we will want the Customer fields to relate to companies in the portal, but not today. Just want to plant the seed now.
None of these fields will be required.

Confirm Information
![image](https://cloud.githubusercontent.com/assets/12280257/7950257/eb06a392-094c-11e5-8a5a-96228395d399.png)
![image](https://cloud.githubusercontent.com/assets/12280257/7950282/1edb4b82-094d-11e5-93be-e7b03abd8178.png)

Note: I want the founder to be able to edit fields directly from this page instead of going back to the original pages. If that's too difficult then we should send them back.

The workflow should follow the order laid out above. The Complete Sign Up button will lead them to their dashboard and ask them "What their Focus is This Week?"

Also, the current sign up is on a wufoo form. I'm perfectly fine with us integrating the wufoo form into this format as long as the information goes from the wufoo form into our DB. If not, I think we should find the best and easiest way to do it ourselves. The key is to have a more professional and consistent experience starting from the sign up. 

Let me know about comments and questions. Thanks!

**Comment by schrizsz** [comment]
We have already should have form builder and helpers to make these forms. I guess integrating wufoo forms might be as time consuming task than building own.

**Comment by zachpritchard** [comment]
At this point, not sure how relevant this issue is anymore with the ability to invite and confirm, we might test it later but closing for the moment!
