### ISSUE TITLE
As a PM, I want a founder to complete the Request Meeting workflow within the portal so that the process will be automated for introducing them, and we can track the messages

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#27]
The founders will be able to click the Request a Meeting link from the Mentors page or the individual mentor's profile to send a message to them about a meeting. This workflow runs similar to the current Connectory workflow- the founder will provide some information that will be sent included in an email template from Ravi to the mentor. Here are the wireframes for the Request a Meeting workflow:

Mentors page
![image](https://cloud.githubusercontent.com/assets/12280257/7963737/16123660-09c9-11e5-9b17-580db6ac11b1.png)
Action: Clicks the "Request a Meeting" button from the connection's card

Request a Meeting modal
![image](https://cloud.githubusercontent.com/assets/12280257/7963768/34347da6-09c9-11e5-92a4-89959f75c117.png)
Note: All of the information except for the topic of discussion will be pre-populated from their profile. They will have the ability to edit this information before sending though.

Confirmation
![image](https://cloud.githubusercontent.com/assets/12280257/7963812/7b68b980-09c9-11e5-8a1d-bd143d52595c.png)
Note: We must have these actions logged and allow founders to see Meetings Requested. I will provide wireframes for these next week

Also, I will provide a template for the actually email from Ravi to the mentor as well as the email that connects the founder with the mentor this week.

Let me know if you have any comments/questions. Thanks!

**Comment by zachpritchard** [comment]
@VeikoSoomets 

Email Info
Login: mia@alchemistaccelerator.com
Password: Alch3m1$t


Template 1: Initial Email Sent from Form
--
To: [Mentor You Are Requesting To Meet.Email]
From: mia@alchemistaccelerator.com
cc: ravi@alchemistaccelerator.com; felicia@alchemistaccelerator.com
bcc: zach@alchemistaccelerator.com
Subj: Alchemist Mentoring Meeting Request with [Requester.Company Name]

Dear [Mentor You Are Requesting To Meet.First Name],

We have you listed in the Alchemist Accelerator directory as a mentor prospect available for one-off mentoring sessions with our founders with the request that we broker connections for each meeting with your consent -- hence we send an email for each request. [If you would prefer to sign up as a regular mentor where you can bypass these one-off emails, and we automatically send mentees to you on a scheduled basis (e.g. once / every other week), please reply to this email. To unsubscribe from mentoring requests, please reply to this email.]

On behalf of Ravi Belani, I was emailing to see if you would be up for taking a mentoring meeting with the following Alchemist founder:

[Requestor.First Name] [Requester.Last Name] ([Requester.Email]), co-founder of [Requester.Company Name], requested to meet with you to discuss this, in their words:
[Requester.What would you like to discuss?].

A quick description on [Requester.Company Name] is below. Please just CLICK HERE<link to connect email> to be connected with [Requester.First Name]. If you're not interested, please just reply directly to me.

With thanks,

Mia


[Requester.Company Name] : [Requester.Company Description]

[Requester.Company Name] : [Requester.Team Description]

[Requester.First Name] [Requester.Last Name]’s Background: [LinkedIn Profile]
--

Template 2: Follow up Email from CLICK HERE<link to connect email> in first email

Reply All To First Email
--
To: [Add Requester.Email]

[Requester.First Name], [Mentor You Are Requesting To Meet.First Name] -

I wanted to connect you two.

[Requester.First Name], please meet [Mentor You Are Requesting To Meet.First Name] [Mentor You Are Requesting To Meet.Last Name], who's happy to set up a mentor meeting with you.

[Mentor You Are Requesting To Meet.First Name], please meet [Requester.First Name] [Requester.Last Name], [Requester.Title] of [Requester.Company Name].

Emails above!

Best to each,

Mia
--

Let me know if you have any questions. Thanks!

**Comment by VeikoSoomets** [comment]
@zachpritchard Did I miss something or for some reason I am not able to find the 'Team Description' field from the company view?

**Comment by zachpritchard** [comment]
@VeikoSoomets 

You're not missing anything. We actually didn't include it in the first iteration. If possible, let's add it as a field on the Company profile for Startups and include it in the Team section on the profile. Design below.

![company_profile-team_description](https://cloud.githubusercontent.com/assets/12280257/9426230/eb9da24e-48e7-11e5-8721-a91893e8eb96.png)

Let me know if you have any more questions. Thanks!

**Comment by VeikoSoomets** [comment]
@zachpritchard I also have a question about the radio button which is: Include your Executive Summary / One-pager. Does it mean that founders should be able to have a place for a onepager in their profile pages? Maybe you can explain this button's idea a little bit.

**Comment by zachpritchard** [comment]
@VeikoSoomets 

Eventually we'll add it to their profile. For now, let's just provide them the option to attach it to the message that goes out the Mentor. That being said, we need the document they upload to attach to the message that is sent. Does that make sense?

**Comment by VeikoSoomets** [comment]
That makes sense. But for now maybe we should hide the radio button then? So if founder wants he can attach it but there is no one-pager to include from their profile page.

**Comment by zachpritchard** [comment]
@VeikoSoomets 

This looks awesome, and works great! There are some changes mostly from stuff that Kristian and I worked through on the "Connect Me" message on Monday.

Testing notes:

General
- Change the header of the message to New "Request Meeting" message

Changes to email templates
Initial request
- Add the additional people to the emails:
     - cc: ravi@alchemistaccelerator.com, felicia@alchemistaccelerator.com
     - bcc: {first admin email} same as Connect Me @schrizsz 
- Use only first name in introduction
     - Right now "Dear Kristian Liibert,"
     - Change to "Dear Kristian,"
- Additional changes to bracketed section in Google Doc link
     -  https://docs.google.com/document/d/1eOpkN8csJf3I2OZGCTX7PBVTbs2a56G_BwVN8-p2OpA/edit?usp=sharing
- Lowercase "click" before "here" link
     - Ex. "click HERE" 
     - Note- keep the HERE capitalized
- Change "connect with [Full name]." to just first name
     - Right now "connect with Kristian Liibert."
     - Change to "connect with Kristian."

Introduction
- Add the additional people to the emails:
     - cc: ravi@alchemistaccelerator.com, felicia@alchemistaccelerator.com
     - bcc: {first admin email} same as Connect Me @schrizsz 
- Use same functionality as "Connect Me" when the title is empty
     - Right now reads "None of Alchemist Accelerator" @schrizsz 
- Make the "Best to each," normal text
    - Currently it is bold
- Remove the re-direct to Alchemist.com

**Comment by VeikoSoomets** [comment]
@zachpritchard 
I fixed everything. You can test it. Just remember that all the mails go to ravi and felicia as well then.

**Comment by schrizsz** [comment]
@VeikoSoomets 
- we agreed that we should make the cc fields configurable so that on staging and other testing environments we would not send out cc messages to ravi, felicia

**Comment by VeikoSoomets** [comment]
@zachpritchard 
I managed to add the cc fields as name 'cc_emails' to settings. Please test it. It worked for me in my machine.

**Comment by zachpritchard** [comment]
@VeikoSoomets @schrizsz 

As discussed during sprint planning, looks good on staging!
