### ISSUE TITLE
As a Founder, I want to use the connect with customers and investors in the portal from a card or on a person's profile so that I can get product feedback, potentially new sales or fundraising leads

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#28]
This feature is the same as the current Connectory workflow. The new workflow is the Connect Me to customer or investors workflow- the founder will provide some information that will be sent included in an email template from Ravi to the customer. Here are the wireframes for the Connect Me workflow:

Customers page
![image](https://cloud.githubusercontent.com/assets/12280257/7964141/21d86d96-09cb-11e5-8417-cc202d6d0101.png)
Action: The founder clicks the "Connect Me" button to the founder

New "Connect Me" Message modal
![image](https://cloud.githubusercontent.com/assets/12280257/7964189/59e82e9c-09cb-11e5-9b47-1f3c8c8e67a4.png)
Note: The modal will show what the actual message will look like with From, To and Subject. The underlined items in the message will be links to Company or Individual LinkedIn pages from their profiles.

New "Connect Me" Message modal scrolled down
![image](https://cloud.githubusercontent.com/assets/12280257/7964305/db6f680e-09cb-11e5-9287-c066e4e1474a.png)
Note: The underlined Click Here button will be the action button in the email sent to the mentor. It will automate an introductory email between the founder and the customer from Ravi.

Confirmation
![image](https://cloud.githubusercontent.com/assets/12280257/7964335/0c8d7070-09cc-11e5-9771-11752e3f38d7.png)
Note: These Messages will be in a Sent section for later review. If the Customer decides to accept and connect, the Message should move to a Connected section.

Now that you have access to the old Connectory, you will be able to see how the original function was built. I'm not sure if it will necessarily directly translate and be usable in our portal. Let's discuss though once you've looked it over.

Also, I will provide a template for the actually email from Ravi to the customer as well as the email that connects the founder with the mentor this week.

Let me know if you have any comments/questions. Thanks!

**Comment by schrizsz** [comment]
time estimate if done #

**Comment by zachpritchard** [comment]
From Sprint Planning 7/22:
- Link to person
     1. LinkedIn
     2. Text
- Link to Alchemist in body
- Company name in subject

**Comment by schrizsz** [comment]
- The "Connect me" button does not work after a search
- Show "Connect me" in the user's profile

**Comment by zachpritchard** [comment]
Looks good :)
