### ISSUE TITLE
As a Founder, I want a weekly prompt to choose my focus so that I'm confident the recommended connections are relevant 

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#29]
The founder will receive a modal to choose their focus for the week. The weekly prompt resets every Monday morning and triggers upon their first login for the week so if they login for the first time on Tuesday, it will still prompt them.

Here's the wireframe for the modal:
![image](https://cloud.githubusercontent.com/assets/12280257/7991080/6cb28f9c-0aaa-11e5-830f-65bd4d216103.png)
Note: The recommendations that show up will run off their selection, which is outlined in Issue #22 

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
@VeikoSoomets The user should only be able to choose only one option. Right now, I can select multiple options. Thanks!

**Comment by schrizsz** [comment]
@VeikoSoomets when I click "No thanks" it switches me to "None" but it does not refresh the view. I think "No thanks" should not switch to None but close the modal without changing my focus. If the weekly reset has put me on "None" then I will stay there when clicking "No thanks".

**Comment by zachpritchard** [comment]
@VeikoSoomets: Thanks for making it a select one option, great job!
@schrizsz I apologize, but I don't think I was clear about the functionality of the "No Thanks" link.

CHANGES:
- Let's add another option called "Not Sure" and remove the "No, Thanks" link. 
- When "Not Sure" is selected as their focus, please have the connections screen show "Recently Added Connections." This can just random order the most recently added connections to the portal. 

WIREFRAMES:
![image](https://cloud.githubusercontent.com/assets/12280257/8508692/0ffe8e8a-222f-11e5-9737-5d36820f1c7c.png)
![image](https://cloud.githubusercontent.com/assets/12280257/8508694/1bcf4934-222f-11e5-90d4-afc45303da81.png)

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard Please confirm if the following is OK, because Veiko already fixed this. I think we have here is 2 separate functionalities
1) link that closes the modal without doing any changes "No thanks (I don't want to change my current focus)"
2) link that says "Not sure"

What we spoke with Veiko offline and what Veiko already commited before the new wireframes was that when I have sales selected and I click on "change" link next to the header bar's Weekly focus: Sales, Then, without selecting any focus, I click "No thanks" in the popup but It changes me to None (would be logical to stay on "Sales". Now what it does it keeps me on "Sales" focus. But when I don't have any focus currently selected It sets the focus as "None" ( works as expected )

**Comment by zachpritchard** [comment]
@schrizsz: I tested the current functionality that Veiko committed before I added these wireframes. The "No, Thanks" makes sense, but once you select a focus, you can't disable the focus / choose a "Not sure" option though. If it's not how my wireframes show it, we need to provide a "disable" option somehow. 

We'll discuss it tomorrow during standup.

**Comment by zachpritchard** [comment]
@schrizsz @VeikoSoomets 

Let's keep this the same for now. Please just change the text in the box to the follow (all the same except the last paragraph):
"Why do we ask....
Because if we know your focus, we can give you recommendations of connections and resources so you get the right knowledge for your focus today! 

Also, you can change your focus whenever you'd like, and you'll always be able to search and filter independently from the recommendations!"

Once this is complete, let me know and I'll close the issue! Thanks :)

**Comment by VeikoSoomets** [comment]
@schrizsz @zachpritchard 
Text in the box is changed now.

**Comment by zachpritchard** [comment]
From sprint planning 7/8:

From Spring Planning 7/15:

- "This Week's Focus:" to the left of the focus
- It will be one line, centered now
- ex. "This Week's Focus: Fundraising change"
same formatting as is for each part
