### ISSUE TITLE
As a founder, I want to access an Events calendar view and week view from the left side menu

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#3]
Image below shows the Events menu circled:
![founder-dashboard-events_circled](https://cloud.githubusercontent.com/assets/12280257/7626672/a7ba2662-f9c1-11e4-8e1e-1007f491228a.png)

After clicking through Events, here's the calendar view:
![founder-events-calendar_view](https://cloud.githubusercontent.com/assets/12280257/7626678/cdf68488-f9c1-11e4-9ddb-bf6f9c465d1f.png)

In the top right, you can switch to the week view:
![founder-schedule-week_view](https://cloud.githubusercontent.com/assets/12280257/7626684/decd96f2-f9c1-11e4-9287-5c6e868e97f0.png)

I believe, we can just use the Google Calendar API to access the Alchemist Events. Here's a link that might help - https://developers.google.com/google-apps/calendar/

**Comment by schrizsz** [comment]
Here it seems connections, resources and service providers are all separate developments showing a new view and maybe even new db tables each.

**Comment by schrizsz** [comment]
Using the calendar API is somewhat in conflict with the idea of having the events in our own DB as discussed on 13. May planning meeting. 

1) If we take the events from a google calendar we are limited to gcal data structure, being title and summary. Should be really easy with http://fullcalendar.io/js/fullcalendar-2.3.1/demos/gcal.html, 1-2 hours

2) If we have the events in our db we need to create db table and json feed, but we have more possibilites to add more structured data, (eg for who is this event) and gives more flexibility to show the data in searches and custom views. Initially using the same fullcalendar.io will take 2-4 hours.

Which approach should we use. (I would prefer 2) (It would be better if we had one approach thru the site)

**Comment by zachpritchard** [comment]
I really don't mind which solution we use today. The vision for this feature is to eventually be the actual point of scheduling between portal users. They will be able to link their calendar to it so all changes on the portal will be on their normal calendar. That's the vision, but today we just need it to show alchemist events. 

Also, please note that I only want our marketing team to input an event once, whether on the Google alchemist cal or on the portal, but the key is that it will show up on both with the option to export upcoming events to a doc or send as an email. Let me know if you need any more info.

Ultimately, I want you to make the decision on the solution, but just make sure you understand the vision and take it into consideration.

**Comment by schrizsz** [comment]
Hi thanks for insight. Seems gcals as master will work fine now. We'll do
the faster solution 1) today, and if we see difficulties with the approach
we can put more time in and change to the 2) approach.

Kristian Liibert

tel: +372 55617662 (est)
skype: kristianliibert

**Comment by schrizsz** [comment]
@VeikoSoomets 
Use js solution to quicly do this http://fullcalendar.io/js/fullcalendar-2.3.1/demos/gcal.html
Make the calendar id a setting in global settings menu.

**Comment by zachpritchard** [comment]
Here's the Calendar ID for the Alchemist Events calendar:
alchemistaccelerator.com_k54im6k71tmjdlm6qkebcbp5sg@group.calendar.google.com

**Comment by zachpritchard** [comment]
Here are some additional screenshots to help with the views when someone clicks the event.
Here's for the Calendar View:
![image](https://cloud.githubusercontent.com/assets/12280257/7734142/c9f6c65a-fee8-11e4-8b9c-127c4142f96c.png)

And here's for the Week View:
![image](https://cloud.githubusercontent.com/assets/12280257/7734155/d8b196fc-fee8-11e4-944b-8d63a4addc19.png)

Please set up the Register buttons as links that the marketing team can edit as an admin because these links will change for different events created in the future.

**Comment by zachpritchard** [comment]
I just reviewed the Events view on the new v3-portal staging environment. It looks great! 

Some minor changes though. The week and day view need to show the hourly times on the left side of the view so there is a reference of time. I took a screenshot of the current week view and added a sample of the times with lines across in red below:
![events-week_view-times_added](https://cloud.githubusercontent.com/assets/12280257/7801420/43962e62-02d9-11e5-9c87-f38331fa59ca.png)

Also, I'm working on getting make our calendar public so we can test actual events on the calendar, but if I can't we should create a fake calendar to test it on. 

Next steps:
1. Please add the times to the left for both week and day view
2. I'll either give you access to the Alchemist calendar or create a fake calendar with some events so we can test them by today

Thanks!

**Comment by zachpritchard** [comment]
Looks great!

We do need to give a marketing person the ability to add links for the register buttons, but I'll make a new story for it.

Thanks!

**Comment by schrizsz** [comment]
@VeikoSoomets can you comment how to add register links. I think it takes
the link from description and puts under register button?

**Comment by VeikoSoomets** [comment]
Yes. It pretty much takes any link you add to description and puts it under the button.
