### ISSUE TITLE
As an PM, I want a new profile view for the all connections so that I can easily see relevant information

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#31]
The new Founder profile view is similar to the current view. The primary difference is a focus on their experience since it gives a better story of their past. 

Here is the wireframe for the new profile view:
![image](https://cloud.githubusercontent.com/assets/12280257/7992044/4b57a164-0ab1-11e5-8947-f70f57a13d2a.png)
Note: The "A" in the top right corner signifies the Company is in or was in the Alchemist program. The circle should actually have the Alchemist logo in it. 
The "8" in the bottom left corner is the Alchemist Class Number and will only display if it is an Alchemist company. 
The "T" in the bottom left corner shows up if the Founder is Technical. If not, the "T" should not show.

Also, I want to know if we can access a connection's previous information through an API with LinkedIn. If not, we may have to change the layout a bit, but I want to see if it's possible first.

As always, let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
Here we'll need to change the company structure Merge UserCompany -> FounderCompany

**Comment by zachpritchard** [comment]
@schrizsz Here's the revised view for ANY connection type:
![image](https://cloud.githubusercontent.com/assets/12280257/8342243/898cc1ac-1a7f-11e5-80cf-9a81b1177a5b.png)
The primary difference between the different views would be a chance in the button. For ex. "Send Email" button would be "Connect Me" for a customer with the same functionality as the cards on the connections pages.

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard FYI to get the positions from linkedin Alchemist needs to apply for this? As of June all API-s other than login aka "basic profile info" are restricted to be accessible only thru application process: https://developer.linkedin.com/docs/apply-with-linkedin

**Comment by schrizsz** [comment]
alchemistclass not showing in profile view

**Comment by zachpritchard** [comment]
All the info is good. Now, let's clean up the look of this page :)

NEW DESIGN
![individual_profile](https://cloud.githubusercontent.com/assets/12280257/9050987/73fadece-3a09-11e5-98c2-57279e945cc8.png)
Key Changes:
- Remove Company Name from personal info section (redundant)
- Social icons for social profiles
      - If their profile has a linkedin url associated in the DB, show linkedin icon that links. If not in the DB, don't show the icon
- Remove Areas of Interest
     - Split the two sections 50/50
     - the tags are redundant in areas of expertise but I want them to work like the profile cards
- Create "tag" showing for Industry Keywords
- Remove Previous Companies section for now (isn't editable anyway)

We can maybe play around and make the text or pictures bigger, space things out a bit, etc. so it doesn't feel empty. We need to find the right balance!

CSS Notes
Personal Info Section:
/* headshot: (we may want to go bigger, we'll see) */
height: 100px;
width: 100px;
/* connection-name: */
font-family: OpenSans-Bold;
font-size: 14px;
color: #000000;
line-height: 19px;
/* connection_type-icon: */
border: 1px solid #979797;
height: 15px;
width: 15px;
/* connection-title: */
font-family: OpenSans-Light;
font-size: 14px;
color: #000000;
line-height: 19px;
/* city-state: */
font-family: OpenSans-Light;
font-size: 14px;
color: #000000;
line-height: 19px;
/* LinkedIn-logo */
background: #000000;
fa fa-linkedin
/* twitter-logo */
background: #000000;
fa fa-twitter
/* button-background: */
background: #58C9E7;
border-radius: 8px;
/* button-text: */
font-family: OpenSans-Bold;
font-size: 12px;
color: #FFFFFF;
line-height: 17px;

My Story Section:
/* header-text (My Story) */
font-family: OpenSans-Light;
font-size: 18px;
color: #000000;
line-height: 24px;
/* areas_of_expertise_tag-background */
background: #00283B;
/* areas_of_expertise_tag-text */
font-family: OpenSans-Light;
font-size: 12px;
color: #FFFFFF;
line-height: 17px;
/* sub-header-text (my achievements & areas of expertise) */
font-family: OpenSans-Bold;
font-size: 14px;
color: #000000;
line-height: 19px;
/* body-text: */
font-family: OpenSans-Light;
font-size: 12px;
color: #000000;
line-height: 18px;

Current Company Section
/* header-text: */
font-family: OpenSans-Light;
font-size: 18px;
color: #000000;
line-height: 24px;
/* industry_keyword_tag-background */
background: #6D6F71;
/* industry_keyword_tag-text */
font-family: OpenSans-Light;
font-size: 12px;
color: #FFFFFF;
line-height: 17px;
/* sub-header-text (Description, Industry Keywords) */
font-family: OpenSans-Bold;
font-size: 14px;
color: #000000;
line-height: 19px;
/* company_description-text */
font-family: OpenSans-Light;
font-size: 12px;
color: #000000;
line-height: 18px;
/* company-title */
font-family: OpenSans-Light;
font-size: 14px;
color: #4A90E2;
line-height: 19px;

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
@schrizsz 

Notes:
Personal Info Section
/*Profile headshot*/
.main_profilepic 
max-width: 135px;
or 
60px from right and left
40px from top
/*social icons*/
max-width: 17px;
max-height: 17px;
/*button*/
40px from bottom of container
My Story Section
/*container*/
padding: >15px 10px;
/*achievements_field-text*/
font-size: 14px;
Current Company Section
/*container*/
padding: >15px 10px;
/*description_field-text*/
font-size: 14px;
/*company_logo*/
max-width: 110px
This section isn't very response- company logo and name expands to cover text above and below when reduced to mobile

Edit mode:
- State field should have list similar to filter in connections
- Hard to tell that you can add edit areas of expertise
- Also, you can edit industry keywords right now- remove functionality and make it so only can edit when on company pg

We also might want to just put technical aka T icon as an icon next to their name connection type because its not working well and I want it to show on their profile card as well. What do you think?

Minor stuff, but looks great! Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
Also, there's a bug while saving information on the individual profile as well. I tried saving Title, City, and State, and it didn't work.
