### ISSUE TITLE
As a Founder, I want different Company types so that there will be different views based on relevant information

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#32]
The company types will be set up similar to the Connection types to show different information that is relevant and will also be part of the recommendation logic in the future. The company profiles will also display different information based on the type of company.

The 3 company types are:
Startup
Enterprise
Fund

Please let me know if you have any questions. Thanks!

Also, I'm going to create another Issue to show the Startup company type profile following this one.

**Comment by schrizsz** [comment]
we agreed to go with fastest solution with one table

**Comment by zachpritchard** [comment]
@schrizsz 
@VeikoSoomets: I know you're working on the startup profile view so more information below on the complete set of company types.

DESCRIPTION:
Companies will have different views based on their company type whether they're a startup, enterprise, or fund. I standardized the template to make it consistent, but each type will display different information.

WIREFRAMES:
Startup
![image](https://cloud.githubusercontent.com/assets/12280257/8584160/bec0b3ba-2588-11e5-8b16-76cec5822bd8.png)
Enterprise
![image](https://cloud.githubusercontent.com/assets/12280257/8584119/48625f66-2588-11e5-9080-e5b0eab2d6d7.png)
Fund
![image](https://cloud.githubusercontent.com/assets/12280257/8584123/5cc10d40-2588-11e5-9600-c11e796748f0.png)

METRICS:
3+ out of 5 on feedback scale

**Comment by VeikoSoomets** [comment]
Have left column floating and right column scrolling.

**Comment by VeikoSoomets** [comment]
Improvements:
- Fields with None should be blank in the view.
- When in edit mode there should be hover over and also placeholders for the fields.

**Comment by zachpritchard** [comment]
@VeikoSoomets 
Reminder:
- Give admin ability to edit "Company Type"

**Comment by zachpritchard** [comment]
@VeikoSoomets 
I received some feedback that the edit icon on the right side isn't very intuitive. Since it will only be on each user's individual and company profile, let's make it more visible. I just took some screenshots and put the buttons on top below, but we should just shift it down to make a little room for the button up top.

DESIGNS:
On profile when in normal mode, "edit" button above.
![company_profile-edit_button](https://cloud.githubusercontent.com/assets/12280257/9019932/528ada66-37aa-11e5-9dc0-0d5780e95e41.png)

In edit mode, button changes to "save"
![company_profile-save_button](https://cloud.githubusercontent.com/assets/12280257/9019938/77d8f44c-37aa-11e5-8eec-0e3ba15871a9.png)

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
It's close, just a little clean up like the individual profile :)

NEW DESIGN:
![company_profile](https://cloud.githubusercontent.com/assets/12280257/9052036/433aec6c-3a17-11e5-8f2e-b5b93652f693.png)

Key Notes: 
- Icon for company type next to name (need to be able to edit with same effect as now)
     - Startup = fa-rocket
     - Fund = fa-university
     - Enterprise Customer = fa-building-o
- Icons as links to social profiles
     - these are examples but only show ones with links in DB
     - order from left to right: email, web, linkedin, angellist, twitter, facebook (same as in image except the addition of angellist)
- Add title below the Team member's name (same as current portal)
- Removed Annual Revenue in Additional Info Section
     - It should still be a field, but only show when it's filled out. Or just have it say N/A

For other views, there's some slight changes, but same formatting in terms of headers, sub-headers, etc. The only changes will take place in the Additional Info Section. 
Funds:
- Remove current fund
- Place field for choice of "Active" or "Not Active" with "in the market" as the stat-text
- Change "both leads and follows" text to just say "rounds" and, the box field will have options of "Leads & Follows", "Leads", "Follows"
- Change "average check size" to just "average check"

Enterprise
- Remove "Organizational Structure"
- Leave remaining two fields and style like Startup below

CSS Notes
Company Info Section:
/* social_profile-icon */
max-width: 15px;
max-height: 15px;
/* company_description-text */
font-family: OpenSans-Light;
font-size: 12px;
color: #333333;
line-height: 20px;
/* logo */
width: 160px;
/* company_name-text (Xendo) */
font-family: OpenSans-Bold;
font-size: 18px;
color: #000000;
line-height: 24px;

Our Story Section:
/* header-text (Our Story) */
font-family: OpenSans-Light;
font-size: 18px;
color: #000000;
line-height: 24px;
/* sub-header-text (The Problem, Our Solution, Industry Keywords) */
font-family: OpenSans-Bold;
font-size: 14px;
color: #000000;
line-height: 19px;
/* body-text */
font-family: OpenSans-Light;
font-size: 12px;
color: #000000;
line-height: 18px;
/* industry_keyword_tag-background */
background: #6D6F71;
/* industry_keyword_tag-text (Data, Seed, China) */
font-family: OpenSans-Light;
font-size: 12px;
color: #FFFFFF;
line-height: 17px;

Team Section:
/* header-text (Team) */
font-family: OpenSans-Light;
font-size: 18px;
color: #000000;
line-height: 24px;
/* member_name-text (Julian Gay, Dominic Lee) */
font-family: OpenSans-Light;
font-size: 14px;
color: #4A90E2;
line-height: 19px;
/* member_title-text (CEO, CTO) */
font-family: OpenSans-Light;
font-size: 14px;
color: #000000;
line-height: 19px;
/* headshot (might make bigger) */
width: 75px;
height: 75px;

Performance Section:
/* header-text (Performance) */
font-family: OpenSans-Light;
font-size: 18px;
color: #000000;
line-height: 24px;
/* sub-header-text (Achievements, Notable Customers, Customer Wish List) */
font-family: OpenSans-Bold;
font-size: 14px;
color: #000000;
line-height: 19px;
/* body-text: */
font-family: OpenSans-Light;
font-size: 12px;
color: #000000;
line-height: 25px;
/* company_name-link (Salesforce, Google, etc)  */
font-family: OpenSans-Light;
font-size: 12px;
color: #4A90E2;
line-height: 20px;

Additional Info Section
/* header-text (Additional) */
font-family: OpenSans-Light;
font-size: 18px;
color: #000000;
line-height: 24px;
/*stat-square (employees, last round): */
border: 1px solid #000000;
/* stat-field (1-10, Pre-Seed) */
font-family: OpenSans-Bold;
font-size: 16px;
color: #000000;
line-height: 22px;
/* stat-text (employees, last round) */
font-family: OpenSans-Light;
font-size: 14px;
color: #000000;
line-height: 19px;

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
@schrizsz 

Notes:
Company Info Section
/*company_logo*/
max-width: 135px
max-height: 135px
/*description_text*/
font-size: 14 px;
Additional Info Section
For Fund- Change "Active"/"Not Active" text "in the market" to "investing"
For Startup- Add "Active"/"Not Active"  field with text after the field as "fundraising"
For Enterprise - Add "Active"/"Not Active"  field with text after the field as "acquiring" 
Fund Overview, Company Overview, Our Story Sections
/*field_text (Investment Criteria, The Problem, Our Solution, What We Do)*/
font-size: 14px;
Team Section
Make company types have a section name of Team (ex. Fund is not Relevant Team Members so change to "Team")
/*profile_pic*/
max-width: 115px;
max-height: 115px;
Name isn't spaced right on fund view
Performance Section
/*field_text (Achievements)*/
font-size: 14px;
/*notable_customers & customer_wishlist companies*/
font-size: 14px;
Companies on separate lines
Links to companies
Portfolio Companies & Competitors Sections
/*company_logo*/
max-width: 115px;
max-height: 115px;
/*company_name*/
font-size: 14;
font-weight: bold;

Editing
- Make Last Round Raised field a selection with the following choices:
     - Pre-Seed, Seed, Series A, Series B, Series C, Series D
- Text for all fields (company name, description, etc - across all individual and company profiles) should move the word to the next line instead of cutting words in half when scaling down responsively

I know it looks like a lot, but mostly cosmetic. Overall, looks great :) 

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
better to test all of these on staging-portal because I've completed the migration
