### ISSUE TITLE
As a Alchemist Operations Team Member, I want to move a contact to another company so that he or she is with the appropriate company

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#35]
Danielle added a team member, Cindy Le, to the Portal within a company, RageOn, Inc., and for some reason, Cindy was added to Alchemist Accelerator. I then tried to move her to RageOn, Inc. within the admin portal, and the field didn't recognize the company even though it showed up and you could select it. 

Here's a screenshot of the error when trying to switch the company:
![screen shot 2015-06-04 at 3 55 33 pm](https://cloud.githubusercontent.com/assets/12280257/7996333/1667152a-0ad4-11e5-9c46-706881876556.png)

And here's the screenshot to prove the company exists:
![screen shot 2015-06-04 at 3 56 09 pm](https://cloud.githubusercontent.com/assets/12280257/7996337/211e1ffe-0ad4-11e5-8b0d-b5db6409d56d.png)

My initial thoughts are that when Danielle added Cindy, it knew Danielle was logged in so automatically added her to Alchemist. I'm not sure if that's the case, but that's the only reason I could think of. 

Overall, let's make sure:
1. Check that founders can add team members to their companies
2. Check that Alchemist Admin can add team members for other companies and move contacts to different companies
3. Make sure new companies are logged correctly in the Database and work within the appropriate fields

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
Did she use the Add team meber button under alchemist?
Or Add new founder (top menu) for admin use?

Kristian Liibert

tel: +372 55617662 (est)
skype: kristianliibert

**Comment by zachpritchard** [comment]
She used the "Add Team Member" button while on the RageOn, Inc. company page

**Comment by schrizsz** [comment]
Sorry just read the email, it had some info missing.  You are right the add new team member works so that it takes logged in users company. 

The move to company did not work because there was a space in the end of the company name, I made a fix for this.

The admin can add a user with the top menu, (it also sends invite email), if wanted I can make a fix for this "Add Team member" for admin also?

**Comment by schrizsz** [comment]
Agreed in the meeting that we should remove the non working/ not necessary fields from the admin "Add founder"

**Comment by schrizsz** [comment]
I made it also so that the Admin should now be able to use the "Add new team member" button on any company.

testable on staging-portal.alchemistaccelerator.com

**Comment by schrizsz** [comment]
Add automatic refresh after changing the company

**Comment by schrizsz** [comment]
in staging

**Comment by zachpritchard** [comment]
@schrizsz When refreshes on staging, it deletes all the founder information that was stored. Please change so that information stays, and the company just changes. They can change this information on their own, but the areas of expertise and fun facts won't change anyway.

Thanks!

**Comment by schrizsz** [comment]
Hi

This does not happen to me. Can you retest this? Or elaborate on how this
happens. I use this super simple screen recorder (also our testers use
this) (it auto uploads so you can just copy paste link) + you can get the
gif which should be attachable in git issue
http://recordit.co/latest

Kristian Liibert

tel: +372 55617662 (est)
skype: kristianliibert

**Comment by zachpritchard** [comment]
@schrizsz I re-tested the feature and it works fine. I'm not sure what happened when I tested it originally. Anyway, push live whenever you're ready. Let me know when you do so I can do a live QA before we close the issue. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard i've put these to live properly (found one detached, local only, branch), please check and close
