### ISSUE TITLE
As a PM, I want all connections data uploaded to the DB so that we can test real data and optimize the migration process

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#36]
The connections data is organized by the fields shared in #30. It's not exactly the same fields because I had to add some as I organized the data. These columns are representative of all the fields we'll need. You will notice there's a bunch of Connection Type Columns. The most important one and driver of the connections type in the DB is Connection Type 1. Most of the other are blank, but we do want to capture the ones that want to have multiple roles within Alchemist. We just want to give them a primary role. 

Here's a link to the connections data file:
https://drive.google.com/file/d/0BwaXE7ECjAJHU2V4MHk1cHJmWjQ/view?usp=sharing

Note: The file has columns for Areas of Expertise and Areas of Interest. The Areas of Expertise should be based on the founder tags, and the Areas of Interest should be based on the company tags. You might want to leave these fields out of the import for now, and I'll provide these using our new tags as a follow up. If you find a way to import it where it can convert similar words to the right tags, go for it. Otherwise, let's hold off.

Finally get to use some real data. I'm pumped! Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
[Connections_to_import_companies.csv | uploaded via ZenHub](https://files.zenhub.io/5595667de9607afe23951b6c)

**Comment by zachpritchard** [comment]
@schrizsz 

DESCRIPTION:
I went through all the connections that filled our areas of expertise from the connections data and translated their answers into our tags. Through this process, we have additional tags to add (89 to be exact). You'll see a tab in the sheet labeled "connections" that has the email, some additional information, and then columns (E-N) with tags for each connections. Additionally, there is a tab in the sheet labeled "tags" that has all the tags. I highlighted the new ones to be added with yellow. 
Note: The exported list of tags and founders had lots of additional tags that should have been removed. When I go through the Manage Tags section though, it's all the right tags. Do you know why that is? Do we have additional information in the DB somewhere? Just curious, mostly because I don't want the DB to have a bunch of useless data in it.
Also, the V3 portal is loading super slow and doesn't pull up company or connection profiles. I'm guessing you're still working on it. If not, do we need to find a solution moving forward?

DOCS:
https://docs.google.com/spreadsheets/d/1j9kMsVJidClusEDVZvmehO5Xi6SopG_q7tsYh-U4NUo/edit?usp=sharing

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
inline:

> DESCRIPTION:
> I went through all the connections that filled our areas of expertise from
> the connections data and translated their answers into our tags. Through
> this process, we have additional tags to add (89 to be exact). You'll see a
> tab in the sheet labeled "connections" that has the email, some additional
> information, and then columns (E-N) with tags for each connections.
> Additionally, there is a tab in the sheet labeled "tags" that has all the
> tags. I highlighted the new ones to be added with yellow.
>
Good format, easier for me, I'll clean up the tags, and let you know.

> Note: The exported list of tags and founders had lots of additional tags
> that should have been removed. When I go through the Manage Tags section
> though, it's all the right tags. Do you know why that is? Do we have
> additional information in the DB somewhere? Just curious, mostly because I
> don't want the DB to have a bunch of useless data in it.
>
 Hi, it was because I did not delete the old (right) tags before the import
just added the new ones, but forgot to add one line to import script that
assigns a type to the imported tags. I added the type now so they should be
visible.

> Also, the V3 portal is loading super slow and doesn't pull up company or
> connection profiles. I'm guessing you're still working on it. If not, do we
> need to find a solution moving forward?
>
Hi I have fixed the issues there were a couple of js loops that were going
nuts with that many elements and delayed with the final loading of the page.

**Comment by schrizsz** [comment]
I got it working again, but need to migrate the other connections again @zachpritchard

**Comment by zachpritchard** [comment]
Great. Let me know when they're all back in. Thanks!

**Comment by zachpritchard** [comment]
From standup 7/27:
- Duplicate connections for customers

**Comment by schrizsz** [comment]
https://docs.google.com/spreadsheets/d/1pwZfXATxnX7YtDuCzRKZsUizjlf-fmjqDfQtYvzI5mI/edit?usp=sharing

**Comment by zachpritchard** [comment]
@schrizsz 

I created a copy of the connections data in a new tab called connections_data.csv-ZP_revised., I removed some mentors that no longer are in the program, added a bunch of cities and states for mentors, changed some names based on how we present them today, added to Invests field, and added 2 columns at the end.

The 2 columns are:
- Angellist Link = a link to their angellist profile 
     - Include as an icon on the profile page with icon fa-angellist
- Button Link = Has the type of button with an associated hyperlink

We can discuss today after your concert. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard 
I can't get the actual url (in gdocs) the angellist link you posted, could you unlink it in excel? to have only the actual link as text and no button text (when I get csv now I only get the "Book a Slot" and no link/ I can deduce the button text from the link :)

**Comment by zachpritchard** [comment]
@schrizsz 

I'm getting an error and can't access staging. Screenshot below:
<img width="1358" alt="screen shot 2015-08-09 at 10 18 34 am" src="https://cloud.githubusercontent.com/assets/12280257/9156023/90285e8e-3e80-11e5-925c-6ce401d92897.png">

**Comment by schrizsz** [comment]
Sorry, my bad, now it should be ok
