### ISSUE TITLE
As a Founder, I want to filter and search for Connections so that I can find who I want based on my own criteria

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#39]
The founder will be able to search or filter the Connections on their own that will be separate from the Recommendations.

Recommended connections wireframe:
![image](https://cloud.githubusercontent.com/assets/12280257/8367453/2ae55a86-1b53-11e5-8c12-b1fdf379cec7.png)
Note: There is now a show search button in the top right of the screen.

Search displayed wireframe:
![image](https://cloud.githubusercontent.com/assets/12280257/8368339/cb38a70e-1b5d-11e5-8ec3-4f8661612f39.png)
Note: When a founder searches, each word or phrase will become a keyword search, which will be the same as if they choose from the filters.

Search in-progress wireframe:
![image](https://cloud.githubusercontent.com/assets/12280257/8368343/d3d2806a-1b5d-11e5-9484-fbd883647935.png)
Note: When a founder opens clicks drop and it opens (similar to above), they should be able to choose 
multiple items and if an item is all ready selected, it should show that it is all ready selected.

Search performed wireframe:
![image](https://cloud.githubusercontent.com/assets/12280257/8368346/db0e9bc0-1b5d-11e5-8a27-63bd5d05a15c.png)
Note: This just shows the results. 

Overall, this functionality exists that searches the connections and the drive in the founder directory 2.0. Let's make it exclusive within and exclusive to connections and have filters. Also, one slight difference from the current search in Founder Directory- the current portal performs a new search when you click on a tag like this http://g.recordit.co/s2c7bsLfot.gif. With this new search, the founder should click a tag and it will add this as part of the search so you would have 2 search keywords instead of searching just the one tag.

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
from standup:
- search connections only
- when picking from drop downs, only search that field
- when typing searches, search all (name, title, company, areas of expertise, company industry keywords, etc. = same as general search)

**Comment by zachpritchard** [comment]
@schrizsz I just did a test of the search and filter feature with the founder data. Some quick notes in case you aren't aware.

Current
- The filters aren't working :(
- Also, when searching by query, the results are shown within founders column. We want them shown left to right removing the silos (more to show that a search was performed).
     - Present them similar to the cards on the mentor, founder, etc page

Changes (don't get mad)
- Add a filter: Technical with Yes or No in the drop down
- Replicate filter on Connections pages (Mentors, Customers, Investors, Founders)
     - Remove the "Type of Connection" though since it wouldn't be applicable

Let me know if you have any questions or there are any issues. Thanks!

**Comment by schrizsz** [comment]
>
>
>
>    - Also, when searching by query, the results are shown within founders
>    column. We want them shown left to right removing the silos (more to show
>    that a search was performed).
>       - Present them similar to the cards on the mentor, founder, etc page
>
> The idea was that when you search by e.g tag it would show the mentors,
 founders, investors in the columns. If the user chooses 1 type it should
be ok, otherwise do You think it's a bad idea to show different types
separated when the search has been performed.

>

**Comment by zachpritchard** [comment]
@schrizsz 

First, it's a not a bad idea! I actually thought it was an interesting approach. I want you to bring up these things so we can talk to our users and test these assumptions.

Saying that, I just received founder feedback firsthand, and they confirmed my thoughts that they'd prefer to receive the general results, meaning not separated by type. It just makes more sense to most users from how search exists today.

**Comment by zachpritchard** [comment]
@schrizsz This looks great, and we're close! Here are my notes from testing:
- Search should be open as a default with the option to hide
- Cards look clean for founders, but all other connection type still have the company cascading onto the second line, which hides the button and profile link
<img width="973" alt="screen shot 2015-07-19 at 9 04 29 pm" src="https://cloud.githubusercontent.com/assets/12280257/8769784/d10032a6-2e59-11e5-81b7-1b16009766b5.png">
- The search should have the following order in terms of logic:
     1. Most number of matching tags
          - the connections with more tags overall should come first ex. if 2 different connections match 4 tags, then if one has 6 tags total and the other 10 total. The 10 would show first.
     2. Most number of tags in general
- Search window has an “undefined” tag when you first open the search
<img width="1360" alt="screen shot 2015-07-19 at 8 35 40 pm" src="https://cloud.githubusercontent.com/assets/12280257/8769706/5fd4bf6c-2e58-11e5-8e53-9d6a752b445a.png">
- All areas of expertise should load all at once
     - Currently it loads as you scroll, but this can be deceiving if they only scroll a couple down they think that there aren't that many
- Add (x) to searched tags so they can remove one at a time regardless of order
     - Currently they have to put the cursor in the search bar and use the arrows to highlight then backspace
- There’s an issue with the tag search… example in the gif (I also tested with other tags)
http://g.recordit.co/E7IFoZI84X.gif

Let me know if you have any questions or we can just discuss tomorrow. Thanks!

**Comment by zachpritchard** [comment]
From Standup 7/20:
- Narrow search with multiple queries instead of broadening
- Hide prefix such as query: or tag: 
- Distinguish filters and searches by background color
     - Queries should have the same color as is - gray background
     - Filters (all) should have light blue - R:157, G:223, B: 239

**Comment by zachpritchard** [comment]
This looks great! I actually got enjoyed playing with it :)

Testing notes:
- Technical still doesn't work in the filter
- It appears the search is limited to 10 results
      - We can show 10, but if there are more, they should be able to go to the next page of results
      - Ex. Connection type "Mentor" only shows 10 but there are more mentors in the DB
- "x" missing for searches/tags on Mac Hi Res Screen (low priority)

Improvements
- Let's add a "Company" Filter that pulls from the company DB
     - Similar to the Customer Wishlist field
- Slight change in order of filters to below
     -  Customer, Areas of Expertise, Company, Technical, Location 

There will be CSS changes, but they're in #46. Thanks!

**Comment by zachpritchard** [comment]
@schrizsz 
I like the Companies addition, and new order! I have some comments though. See below...

Recording 1: http://g.recordit.co/bcfVYH9Lgf.gif
Testing Notes
- Both Areas of Expertise and Companies filters aren't loading when you want to search
- Search isn't working with some queries
     - "python" in the example within the recording

Recording 2: http://g.recordit.co/vF1xZ3wIad.gif
Testing Notes
- Search is slow
- 7,000+ pages all below
     - Not sure how there are so many pages, but if so, we need have a default where it shows 10 pages
     - Typically sites will have 10 pages then "..." and show the last page and then the next button

Recording 3: http://g.recordit.co/2DArH2qVA1.gif
Testing Notes
- Technical filter works great
- When I add a connection type (in this case "Customer"), doesn't change the filter at all when it should narrow it down

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
Testing Notes
- Search still has bugs
     - Choose AdTech Areas of Expertise and no one shows, but tag manager says their are 3 people associated

**Comment by schrizsz** [comment]
@zachpritchard this was fixed by fixing the migration scripts (can be checked on staging-portal)
