### ISSUE TITLE
As a founder, I want to have a Focus for the Week in the header bar to help determine recommendations for connections and resources

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#4]
Please see the center of the header bar in the image below:
![founder-dashboard](https://cloud.githubusercontent.com/assets/12280257/7616678/2d187dfc-f95b-11e4-876c-eb5fd1007729.png)

I guess for future there should be types priority order and tags to match when we define the focus

**Comment by schrizsz** [comment]
Should it be possible to add focuses from admin panel?

**Comment by zachpritchard** [comment]
No, we will not need to add new focuses from the admin panel. We will start with 4 focuses: 
Customer Development
Product
Sales
Fundraising

**Comment by zachpritchard** [comment]
I reviewed this feature on the v3-portal environment- looks great! 

We may want to move the "change" button to below the focus, but I want to get feedback from the founders first. I'm going to close the issue and I'll create a new issue to move that button if necessary after I receive feedback. Thanks!

**Comment by zachpritchard** [comment]
From sprint planning 7/8:
- "This Week's Focus:" to the left of the focus
- It will be one line, centered now
- ex. "This Week's Focus: Fundraising change"
     - same formatting as is for each part
