### ISSUE TITLE
As a Founder, I want to be able to Request A Meeting or Book A Slot with a Mentor from their card or profile view on the portal so I can reach out or schedule a meeting with them right away

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#41]
DESCRIPTION:
The Founder will go through the same process as today, but instead of actually going to a mentor spreadsheet (embedded in the portal), the founder can go straight to the page to fill out the form from the portal or go straight to that mentors appointment calendar.
Note: The Google sheet has additional information that may be unnecessary, but the key columns are "Button Label" (Column E) and "Button Link" (Column F). 

DOCS:
https://docs.google.com/spreadsheets/d/1xQWBugNSckD8RnIaBFnfvf8qX41dlT6E3Gr_E36WIi0/edit?usp=sharing

METRICS:
Percentage of Mentor Requests and Scheduled Appointments in the portal vs the current sheet
Maintain current functionality

Let me know if you have any issues. Thanks!

**Comment by zachpritchard** [comment]
Discussed in Standup 7/10:
- Add URL to Investors that are Institutional for Connect Me button
    - https://influencerseries.wufoo.com/forms/request-to-email-funds/
- Add URL to Investors that are Angel for Connect Me button
    - https://influencerseries.wufoo.com/forms/request-to-email-alchemist-angel-directory/

**Comment by zachpritchard** [comment]
Sorry for the confusion, but I removed the previous comment that we discussed in standup. We will just use #28 to address both individual customers and investors since that's the existing workflow in the connectery. I'm creating another issue for fund and angel blasts, which is a bit different since it's actually done on the company level.

**Comment by zachpritchard** [comment]
Testing Notes
Changes:
- Switch button text “Request to meet” to “Request Meeting"
- Links are not working for the "Book a Slot"

**Comment by schrizsz** [comment]
while I imported the links the emails matched only 3 users in the v3-staging environment, are these emails correct?

**Comment by schrizsz** [comment]
migrations should have fixed this
