### ISSUE TITLE
As a PO I want to have changes ready for review on staging server as soon the developer commits them.

### ISSUE THREAD

**Issue by schrizsz** [AlchemistAcc/portal#5]
So we should set up 
- a git webhook 
- create new venv
- install small  https://github.com/carlos-jenkins/python-github-webhooks in separate venv
- make script to autodeploy staging on staging-portal
- make script to autodeploy v3 on v3-portal

**Comment by zachpritchard** [comment]
@schrizsz  If you feel confident that this feature is working, please go ahead and close the issue. Otherwise, let me know if there is another way I or you can test it so we can move forward. Thanks!
