### ISSUE TITLE
When you switch a connection type from Founder to another type (Mentor, Customer, Investor) for the first time, they don't show up in the connections search

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#64]
DESCRIPTION
As we discovered during standup, when you change the connection type from Founder to another type, they no longer can be found in the search. I tested a bunch of other connections and narrowed it down to the first time you switch a Founder (pretty sure via invite) to another connection. 

Ex. If I invite Veiko as a Founder then switch him to a Mentor, you can't find him in the search. If I change him back to a Founder though then switch him back again to a Mentor, he'll show up.

Let me know if you have any questions. Thanks!

**Comment by VeikoSoomets** [comment]
@schrizsz 
I also had this issue some days ago. It is because the 'active' field is not set to true when changing connection type.
