### ISSUE TITLE
As a Founder, I want to auto complete for search so that I can find names, areas of expertise, companies, etc. quickly

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#78]
DESCRIPTION
Founders are currently just searching blind for random info. We want to provide some context so they can find what they're looking for quicker. Therefore, we'll have auto-complete for search that shows names (where they can click directly to someone's profile) and areas of expertise, companies and other filter items (where it adds as a filter vs just a general search). 

DETAILS
- Show 10 search results
    - Prototype shows 5 results, but probably a better experience showing 10
- Scroll beyond the 10 showing, keep the same size of box though
- If less than 10, box should size to number of results
   - Ex. If only 3 auto-complete for a search, the box should only grow as big as the 3 options

PROTOTYPE LINKS
Name Search:
https://invis.io/FT4B5GKG9

Filter Search:
https://invis.io/EK4B5JHUG

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
I left the perform freeform search as the first option, so the default action when pressing enter would stay the same.
I'm also showing more than 10  on occations let me know if thats not ok, I can put in some more sophisticated limiting.

**Comment by zachpritchard** [comment]
@schrizsz 

First, looks great!

Main note so far: When I search then put a space, it doesn't always show the matches with the letter of the last name. It works sometimes

- Ex1: search john then add space and t then t last names don't show
   - http://g.recordit.co/vZAEFkPQ6O.gif
- Ex2: search chris and shows some results then when I add c, it shows another name that didn't display and not an original result that displayed at first but still meets the criteria
   - http://g.recordit.co/vR3122xXCa.gif

**Comment by zachpritchard** [comment]
also, let's change the free form search
- Now: (perform freeform search)
- Change to: (general search)

**Comment by zachpritchard** [comment]
Thanks for making the changes! A couple more notes:
 
1) I'm seeing duplicates when searching for certain people. Is this only applicable to staging? Whether it is or not, we need to make staging identical to production so our testing is a true demonstration of production.
   - Ex1: Jeremy Baker - http://g.recordit.co/eYuEEwONRy.gif
   - Ex2: Amit Joshi - http://g.recordit.co/n6J60Qen7S.gif

2) Connection not appearing when I search. I'm only finding this for one connection but who knows if there are others.
   - Ex: Andrea Faz - http://g.recordit.co/wIsoZ7e1CC.gif

3) When I search "first name" <space> "last initial or name", it doesn't show any results. Even though we're showing auto-complete for names, we still want a general search of first and last name to show all the results
   - Ex: john t - http://g.recordit.co/5F1mA1t3n0.gif

**Comment by zachpritchard** [comment]
Looks great and works even better so closing! :)
