### ISSUE TITLE
As a Founder, I want a more intuitive profile editing process so I can make lots of changes on my profile quicker

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#81]
DESCRIPTION
As discussed during Spring Planning, our profile editing is really tedious and not very intuitive. Let's improve it by making the editing more clear and allowing founders to edit multiple fields quickly by tabbing.

DETAILS
We spoke about this briefly, but it doesn't have to look exactly like the prototype in terms of time to develop. Here are the key requirements:
- Edit button(s)
    - Clear and intuitive edit button(s) or icons aka pen/pencil for each section or for the entire page
- Fields visibly in edit mode
   - Dashed lines aren't distinctive enough so same as if editing right now is fine but for all in the section
- Tab though fields
   - Whether by section of other way, make it so they can tab through to change fields

PROTOTYPE LINK:
https://invis.io/XR4CYLFFA

Let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
@VeikoSoomets: I didn't see your stand up answers today. Can you please give me an update on the status and timing? Thanks!

**Comment by zachpritchard** [comment]
@VeikoSoomets: Thanks for pushing out the initial editing!

Here's my initial testing notes taking into consideration you're not finished yet:
Individual Profile
- Areas of Expertise
   - When you add a new tag to your areas of expertise, you can't remove it (you can remove ones that were already saved)

Company Profile
- Industry Keywords
   - No (x) to remove tag from profile

**Comment by schrizsz** [comment]
@VeikoSoomets your changes to company search break the typeahead on "Invite founder" http://localhost:6543/add/founder should autocomplete.

**Comment by zachpritchard** [comment]
Testing Notes:

**General**
- [ ] Remove "None" from blank fields
   - We'll add preview text later

**Individual**

- [ ] Add Titles when editing ex. If I'm editing My Story section, it should still have Our Story at the header
_Basic Info section_
- [ ] Can't see save button on 13" mac 
- [ ] Make a set width so there is no cascading/stacking of titles
- Add Fields (name - field type)
   - [ ] Connection Type - dropdown with Founder, Faculty, Mentor, Customer, Investor, Network (below name)
   - [ ] LinkedIn Email - text (below email)
   - [ ] Active - checkbox (2nd to bottom)
   - [ ] Delete Profile - button (bottom)
- Update Field Type (name - new field type)
   - [ ] State - dropdown with US states
   - [ ] Phone number - integer then format on profile as (xxx) xxx-xxxx {ex. (123) 456-7890} if more than 7 add to beginning with plus in front +xx (xxx) xxx-xxxx {ex. +90 (123) 456-7890}
       - If possible, format as they type :)

_My Story_
- [ ] Add paragraph breaks to Achievements

**Company**

- [ ] Add Titles when editing ex. If I'm editing Our Story section, it should still have Our Story at the header
_Basic Info section_
- [ ] Make a set width so there is no cascading/stacking of titles
- [ ] Move Company Type field from Additional Info to Basic Info (below company name)
- Add Fields (name - field type)
   - [ ] Alchemist Company - checkbox or true, false
   - [ ] Class # - dropdown with 0-{alchemistclass from Global Settings} ex. now is 1-12
- Update Field Type (name - new field type)
   - [ ] Founded - dropdown with years 

_Additional Info section_
- [ ] Make a set width so there is no cascading/stacking of titles
- Update Field Type (name - new field type)
   - [ ] Annual Revenue - integer then format as $xx,xxx {ex. $50,000}

_Our Story_
- [ ] Remove length restrictions on The Problem and Our Solution and make sure paragraph breaks work
- [ ] Change "x" in Industry Keywords to the color white (hard to see right now)

_Team_
- [ ] Remove length restrictions on Description
   - [ ] Make sure paragraph breaks work
- [ ] Not searching for names when typing so can't add team members
   - [ ] Make sure still works when adding a space and typing the full name
- [ ] Missing the "Add a New Team Member to the Vault" link
- [ ] Shows a team member of "None" right now when open so please remove
- [ ] Names are stacking in Team section when there is a long name (add "..." if too long)
   - ![screen shot 2015-10-27 at 11 06 46 am](https://cloud.githubusercontent.com/assets/12280257/10767763/fb30704c-7c9a-11e5-86a8-ca58eda7a78f.png)

_Performance_
- [ ] Achievements is showing up with the title Description
- [ ] Remove length restrictions to Description
   - [ ] Make sure paragraph breaks work
- [ ] When I remove a company from the Notable Customers or Customer Wishlist lists, it shows it removed but when I save it's still there

There's a lot of little things and some of it may be confusing so let me know if you have any questions. Thanks!

**Comment by zachpritchard** [comment]
@VeikoSoomets: Looks great! Just some minor changes and most are the same in a bunch of different place.

Testing Notes:

**General**
- [ ] Founder should be able to see other Founders phone numbers (but no other connection type)
- [ ] Can't see full form on 13" mac book- allow me to scroll the whole page

**Individual Form**

_My Story_
- [ ] Allows me to add the same Area of Expertise tag twice when adding Area of Expertise tags (only saves once but confusing)
- [ ] Clear the text when I add an Area of Expertise tag

**Individual Form**

_Basic Info_
- [ ] Add a blank option as part of the dropdown for Alchemist Class

_Our Story_
- [ ] Field titles are different when in edit mode (both display "What We Do")
- [ ] Allows me to add the same Industry Keyword tag twice when adding Industry Keyword tags (only saves one but confusing)
- [ ] Clear the text when I add an Industry Keyword tag

_Team_
- [ ] Allows me to add the same Team Member twice when adding Team Members (only saves one but confusing)
- [ ] Clear the text when I add a Team Member

_Performance_
- [ ] Allows me to add the same Customer in both Notable and Wishlist twice when adding Customers (only saves one but confusing)
- [ ] Clear the text when I add a Customer to the Notable or Wishlist

_Additional Info_\
- [ ] Make Employees column a dropdown with the following options: 1-10,11-50, 51-100, 101-250, 251-500, 501-1000, 1001-5000, 5001-10000, 10000+
- [ ] Make Fundraising options: Yes, No
- [ ] Last Raise not visible after saving

**Remove Fields for Non-Admin**

- [ ] Connection Type
- [ ] Connect Me Quota

**Comment by zachpritchard** [comment]
@VeikoSoomets: Really close! Last few things

Testing Notes:

_General_
- [ ]  Non-admin founder still sees the Connection Type field

**Individual Profile**
- [ ] Country flag not showing up in front of the phone number

<img width="267" alt="screen shot 2015-10-31 at 2 24 45 pm" src="https://cloud.githubusercontent.com/assets/12280257/10865982/3fe6498a-7fdb-11e5-8bad-e8993f12bb66.png">

**Company Profile**

_Basic Info_
- [ ] Logo is added in edit mode, but when i click save, it doesn't show up - http://g.recordit.co/VpEVSrWJ2J.gif

_Our Story_
- [ ] Industry Keywords are spaced out a lot in 2 lines, make the same as before
<img width="239" alt="screen shot 2015-10-31 at 2 26 33 pm" src="https://cloud.githubusercontent.com/assets/12280257/10865991/71fd1b60-7fdb-11e5-8679-47117cdeae39.png">

_Additional Info_
- [ ] When displaying Last Raise field, change text from "Rounds" to "Last Raise"

**Comment by VeikoSoomets** [comment]
@zachpritchard Cannot reproduce the country flag not showing issue in local machine and in staging neither. Maybe you can do video/test with different users/different use cases and let me know again.

**Comment by zachpritchard** [comment]
@VeikoSoomets: No problem! I reproduced with my admin account and test non-admin account.

_Recordings:_
- Zach Pritchard (admin account) - http://g.recordit.co/rhNQiBbOUn.gif
- Smith Maynard (non-admin account) - http://g.recordit.co/Ym7HbaDbnA.gif

Also let's make these quick changes too.

- [ ] Display country flag/code when saved (only shows in edit mode now)
- [ ] Make the phone number a call link by adding "tel:" - Here's more info how: http://www.mobilexweb.com/blog/click-to-call-links-mobile-browsers

**Comment by zachpritchard** [comment]
Look great @VeikoSoomets! Closing the issue :)
