### ISSUE TITLE
After a connection receives Ravi's email to connect and clicks "HERE", let's redirect them to a landing page so they know that it worked

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#83]
DESCRIPTION
Mentors, investors, customers and network connections are confused when they land on the Alchemist website after clicking "HERE" in the email they receive. Let's redirect them to a landing page that confirms the action and tells them to check their email.

IMAGES
Email to the connection (HERE is circled to show you the link)
![screen shot 2015-10-05 at 3 57 51 pm](https://cloud.githubusercontent.com/assets/12280257/10296232/608eab2e-6b7b-11e5-8506-3f238d402672.png)

After they click "HERE"
![connected-landing_page](https://cloud.githubusercontent.com/assets/12280257/10296190/0ef37cae-6b7b-11e5-8fa4-2771e90b4c01.png)

I'm happy to create the landing page if that's easier for you. Otherwise, let me know if you have any questions.

**Comment by zachpritchard** [comment]
@schrizsz 

The "HERE" link in the draft is still a dummy link. Let's make it go to the landing page

**Comment by zachpritchard** [comment]
I see that the dummy link now that goes through to the sample :)

@schrizsz I'm guessing the security hole was that the link sent to the founder was the link to intro. Did you make the "send me a copy" link to a founder the dummy link as well?

**Comment by schrizsz** [comment]
@zachpritchard yes in the copy we now have .../dummy to avoid the user himself accepting

**Comment by zachpritchard** [comment]
@schrizsz great and good catch! add to the next release :)
