### ISSUE TITLE
Google Analytics missing tracking code

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#84]
DESCRIPTION
GA says there's an error with the tracking code. I did the try again feature last week, but it still shows an errors. 

ERROR MESSAGE:
Missing Tracking Code
First seen time: Aug 23, 2015 5:08:16 PM
Last seen time: Oct 4, 2015 9:27:16 AM
No valid tracking code found for property The Vault 1.0's default URL https://portal.alchemistaccelerator.com. Make sure your pages are tagged with a supported version of the tracking code.

Google Tag Assistant Recordings can help you ensure that your pages are properly tagged.
Learn more: https://support.google.com/analytics/bin/answer.py?answer=1086338&hl=en_US

Let me know if you need anything else from me. Thanks!

**Comment by schrizsz** [comment]
I set up permanent redirect to https://vault and changed GA code to expect vault as an url. Should go greener.

**Comment by zachpritchard** [comment]
@schrizsz 

Google Analytics is still showing an error:

Missing Tracking Code
First seen time: Aug 23, 2015 5:08:16 PM
Last seen time: Oct 10, 2015 9:28:21 AM
No valid tracking code found for property The Vault 1.0's default URL https://vault.alchemistaccelerator.com. Make sure your pages are tagged with a supported version of the tracking code.

Google Tag Assistant Recordings can help you ensure that your pages are properly tagged.
Learn more: https://support.google.com/analytics/bin/answer.py?answer=1086338&hl=en_US

Try a new goal
First seen time: Aug 16, 2015 9:46:10 AM
Last seen time: Oct 12, 2015 9:38:59 AM
Analytics can help you set and track your own conversions for high-value objectives like ecommerce transactions, sessions, or pageviews.
Learn more: https://support.google.com/analytics/bin/answer.py?answer=1006230&hl=en_US

**Comment by zachpritchard** [comment]
moving to Pivotal Tracker so closing
