### ISSUE TITLE
As a PM, I want to ensure that Google Analytics is collecting accurate data

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#9]
The notification still exists for an issue with tracking on the New Portal. Here's a screenshot of the issue:
![screen shot 2015-05-19 at 1 19 25 pm](https://cloud.githubusercontent.com/assets/12280257/7713067/15042026-fe2a-11e4-934b-22047bbb093c.png)

I pushed the Verify button, which takes 24 hours, although I think you (Kristian) all ready tried this verification. If so, it actually came back and confirmed the error. I believe the links need to be updated on each page. If so, here's a link to add tags back to the website:
https://support.google.com/analytics/answer/1008080?authuser=1&hl=en&utm_id=ad&authuser=1&rd=1

**Comment by schrizsz** [comment]
It seems that it is fixed now. Lets see if there any other issues with this.

**Comment by zachpritchard** [comment]
GA is showing it as resolved so I think we're good. I'll let you know if I see any discrepancies.

Thanks!
